apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nselec
  labels:
    app: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      nodeSelector:
          type: ssd
      containers:
        - name: dummy
          image: nginx
